# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
