# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0004_comments_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imo_app.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='question',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
