# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0004_feedbackcomment_feedbackvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
