# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0005_auto_20160516_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
