# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0006_auto_20160518_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(default='', max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imo_app.UserProfile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imo_app.Question')),
            ],
        ),
    ]
