# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0009_auto_20160518_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imo_app.Question')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imo_app.UserProfile')),
            ],
        ),
    ]
