# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0011_auto_20160521_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
