# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0012_choice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
