# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0013_auto_20160531_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
