# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0014_auto_20160601_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
