# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0017_auto_20160601_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
