# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0027_auto_20160604_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='total_votes',
            field=models.FloatField(default=1.0),
        ),
    ]
