# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0031_auto_20160604_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(default='', max_length=120)),
                ('birthday', models.DateTimeField()),
                ('gender', models.CharField(default='', max_length=120)),
                ('interests', models.CharField(default='', max_length=120)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imo_app.UserProfile')),
            ],
        ),
    ]
