# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0031_auto_20160604_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
