# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0032_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='male', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
