# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0034_auto_20160605_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(default='', max_length=120),
        ),
    ]
