# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0034_userprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='motto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
