# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0035_auto_20160605_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
