# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0036_auto_20160605_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='total_votes',
            field=models.FloatField(default=0.5),
        ),
    ]
