# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0038_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(default='0000-00-00 00:00[:00[.000000]][EST]'),
        ),
    ]
