# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0038_auto_20160605_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
