# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0039_auto_20160606_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
