# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0043_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_friends',
            field=models.IntegerField(default=0),
        ),
    ]
