# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 03:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0044_userprofile_total_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='relation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 8, 3, 31, 17, 595224, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
