# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0045_auto_20160607_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to='imo_app.UserProfile'),
            preserve_default=False,
        ),
    ]
