# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0046_auto_20160608_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
