# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0050_remove_friendship_friend_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='inappropriate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inappropriate',
            field=models.IntegerField(default=0),
        ),
    ]
