# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0051_userprofile_inappropriate'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='inappropriate',
            field=models.IntegerField(default=0),
        ),
    ]
