# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0052_question_inappropriate'),
        ('imo_app', '0051_auto_20160611_1428'),
    ]

    operations = [
    ]
