# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0053_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
