# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imo_app', '0054_auto_20160612_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_of_service',
            field=models.BooleanField(default=False),
        ),
    ]
